### ISSUE TITLE
how do you document your backends?

### ISSUE THREAD

**Issue by bionicles** [fpereiro/backendlore#1]
do you write API docs in advance? if so, how?

I'd love to use a great working example (for example, if it had a Makefile to run a infrastructure as code Terraform / Pulumi / AWS CDK deployment or something)

**Comment by fpereiro** [comment]
Hi Bion! Thanks for your interest!

I write API docs manually and don't generate them automatically. It takes a bit of discipline, but what I do is document the behavior of the endpoint in terms of inputs and outputs (usually JSON body & JSON reply). Here's an example: https://github.com/altocodenl/acpic#routes . This level of documentation has been very helpful for both design & debugging.

In terms of comments within the code, I try to avoid them as much as possible. For sufficiently stable software, my golden standard would be to perform annotated source code (at least on the server code), but that's now a distant dream. Here's an example of what I mean by annotated source: https://github.com/fpereiro/dale#source-code 

I'm not sure I understand your question about a Makefile to run infrastructure as code; are you referring to doc generation or to a provisioning/deployment process? I'd be glad to clarify further, although I'm far from an expert if it entails the latter.

Cheers!

**Comment by prateekrastogi** [comment]
@fpereiro Please clarify your opinions on fast-scan indentation issues with Python and optional semi-colons permeability with Rust, if it entails you as a backendlore geek. ;-)

**Comment by fpereiro** [comment]
Hi @prateekrastogi ! I have very limited experience with Python and none whatsoever with Rust, so I cannot say anything in either regard...

**Comment by fpereiro** [comment]
Hi @bionicles ! Hope I answered your original questions; if I haven't, or you have new ones, feel free to reopen the issue or create a new one. Thanks!
