### ISSUE TITLE
Sharding is very important for any api when it grows.  How do you do DB Sharding ? 

### ISSUE THREAD

**Issue by miteshsondhi** [fpereiro/backendlore#10]

**Comment by fpereiro** [comment]
Hi @miteshsondhi ! Interesting question! In response to it I just added a diagram of Architecture E and also a section where I put all that I know about database partitioning, which is very little (https://github.com/fpereiro/backendlore#db-partitioning). If you have further questions please feel free to reopen the issue.

Thank you!
