### ISSUE TITLE
Ideas + feedback

### ISSUE THREAD

**Issue by dionjwa** [fpereiro/backendlore#13]
This is great, thank you for putting your thoughts + process down.

I'm in a very similar space. I have my own best practises, and there's a lot of overlap. 

I have an idea, wondering if you have interest:

We have a kind of competition, like if we had cars, and we bring them to a lot, and show them off to each other.

But with deployable systems like we build. We have some regular competition, low stakes, just out own votes and approval.

Where we prioritize things important to ourselves, and learn from each other.

Some shiny things:
- start up a cluster/web service with a few commands
- automatic scaling, from cloud functions all the way to a scaled up cluster
- graphql integration
- typing (e.g. Typescript) front and and back end
- automatic migration of a complex system to different cloud providers, so there's no vendor lock-in.
- automatic access to sane grafana dashboards

What do you think? This is meant to be for fun and learning, not serious. We make it really inclusive, and show-off what we've learned, and help others up the ladder of complexity.

**Comment by fpereiro** [comment]
Hi @dionjwa ! Glad you liked the write-up!

I'm not sure I understand your proposal, though I'm glad to discuss it further. Would this entail doing a sort of competition or showcase of different approaches to the same problem?

My idea here was to show what worked for me from experience, and only that. I would hesitate about recommending things that I don't personally use in real settings and I feel that most of the points you bring up are things that I have never worked with. If I have a car, so to speak, it's not very shiny, and it's the one right in front of you right now :). I also must say that after answering many great questions over the past few days, I'm running out of things to say, so I wouldn't have much more to show other than this and the open source code I am working on.

But I'm definitely interested in hearing about how to help others up the ladder of complexity, so please expand on your idea. Feel free also to contact me directly through email. And of course feel free to reference the ideas here in any context where they might be useful.

Thanks!

**Comment by fpereiro** [comment]
Hi @dionjwa ! I hope to have addressed your concerns earlier; if you want to pursue this further, feel free to comment here or contact me directly. And thanks again for your interest!
