### ISSUE TITLE
Docker instead of Vagrant

### ISSUE THREAD

**Issue by johnoscott** [fpereiro/backendlore#14]
This is a great read - but when I can to the part on using Vagrant I wondered if you had experience using Docker for development, testing or deployment. Is there anything to share ?

**Comment by fpereiro** [comment]
Hi @johnoscott ! Glad you like the document!

At the end of the Provisioning section I mention that I don't normally use Docker and directly run the apps on the host (either locally or on the remote server). In this conversation within a related issue, I go more into detail over this matter: https://github.com/fpereiro/backendlore/issues/11 . I put pretty much all my experience with Docker there :)

As for Vagrant, I only use it when running projects that use software that I don't want installed locally on my host OS. For projects where I fully control the architecture, I use very few programs (node.js, redis) that I already have installed, so I don't need to isolate the development environment.

**Comment by johnoscott** [comment]
Oh sorry I missed the discussion of Docker in the Provisioning section. Thanks for the reply and thanks again for sharing your lore.

**Comment by fpereiro** [comment]
My pleasure! Hope the doc is useful to you. Cheers!
