### ISSUE TITLE
What is "mg"

### ISSUE THREAD

**Issue by jon49** [fpereiro/backendlore#20]
I've done multiple web searches and can't seem to find anything but you :-).

In the code you use it to start/restart/stop your node service. I've been just looking for a way to start multiple applications at once and haven't found anything. In particular `hugo server`. But that isn't your problem, that is mine :-).

Thanks!

**Comment by salesh** [comment]
Hey @jon49 take a look on https://github.com/tj/node-mongroup 
```The mongroup executable is also aliased as mg``` 


mongroup.conf talk in https://github.com/fpereiro/backendlore#provisioning

**Comment by fpereiro** [comment]
Hi @jon49 ! Indeed, as @salesh points out, `mg` stands for `mongroup`. Hope that solves your problem! The installation procedure I outlined (taken from the library) seems to be working for me as of very recently.

Thanks @salesh for the quick reply!
