### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mvpsheng** [fpereiro/backendlore#21]
Bro，i really like your purposes，but i have to say your file is too long to read。

Never mind,Have a nice day!

**Comment by fpereiro** [comment]
My apologies @mvpsheng -- paraphrasing Mark Twain: "I didn't have time to write a short backendlore, so I wrote a long one instead."

**Comment by srijanshetty** [comment]
@fpereiro I think this is the perfect length. I've read it multiple times over the last 2-3 years and incorporated a bunch of advice. Thanks for all the effort you put in!

**Comment by salesh** [comment]
+1 @fpereiro thanks for putting this together. I learned a lot. I come back from time to time to read it again.

**Comment by fpereiro** [comment]
Thank you @srijanshetty and @salesh -- really really glad any of this was/is useful to you.
