### ISSUE TITLE
Don't use /tmp

### ISSUE THREAD

**Issue by anlutro** [fpereiro/backendlore#5]
Using `/tmp` to install mon as well as for logs doesn't seem like the best thing to do, the data is going to get lost if the server ever has to reboot. Just put it in `/opt` instead.

**Comment by fpereiro** [comment]
Hi Andreas -- thanks for your contribution!

Regarding installing `mon`, `/tmp` seems the right place to hold a temporary installation file (that then is deleted as soon as mon is properly installed (`rm -rf /tmp/mon`).

Regarding holding the logs in `/tmp`, it's definitely bad if you're not storing them somewhere else - I added a clarification to this effect in the Notification section.

**Comment by fpereiro** [comment]
Hi @anlutro - just read your issue again today with fresh eyes and I think that both items are responded. Am closing the issue - but please feel free to reopen it or comment if you still feel I haven't addressed your concerns.

Thank you!
